COLUMN LINEITEM FORMAT 99,999,999
COLUMN ORDERS FORMAT 99,999,999
COLUMN CUSTOMER FORMAT 999,999
COLUMN PARTSUPP FORMAT 99,999,999
COLUMN SUPPLIER FORMAT 999,999
COLUMN PART FORMAT 99,999,999
COLUMN NATION FORMAT 999
COLUMN REGION FORMAT 99
SELECT (SELECT COUNT(*) FROM LINEITEM )LINEITEM,
       (SELECT COUNT(*) FROM ORDERS ) ORDERS,
       (SELECT COUNT(*) FROM CUSTOMER ) CUSTOMER,
       (SELECT COUNT(*) FROM PARTSUPP ) PARTSUPP,
       (SELECT COUNT(*) FROM SUPPLIER ) SUPPLIER,
       (SELECT COUNT(*) FROM PART ) PART,
       (SELECT COUNT(*) FROM NATION ) NATION,
       (SELECT COUNT(*) FROM REGION ) REGION
FROM DUAL;
