
-- CREATE TABLE AUTHOR
CREATE TABLE AUTHOR (
	AuthorID		VARCHAR(12)		NOT NULL,
	Name			VARCHAR(50)		NOT NULL,
CONSTRAINT AUTHOR_PKEY PRIMARY KEY (AuthorID)
);

-- CREATE TABLE BOOK
CREATE TABLE BOOK (
	BookID			VARCHAR(12)		NOT NULL,
	Title			VARCHAR(80)		NOT NULL,
	Price			DECIMAL(4,2)	NOT NULL,
CONSTRAINT BOOK_PKEY PRIMARY KEY (BookID)
);

-- CREATE TABLE BOOKAUTHOR
CREATE TABLE BOOKAUTHOR (
	BookID			VARCHAR(12)		NOT NULL,
	AuthorID		VARCHAR(12)		NOT NULL,
CONSTRAINT BOOKAUTHOR_PKEY PRIMARY KEY (BookID, AuthorID),
CONSTRAINT BOOKAUTHOR_FKEY1 FOREIGN KEY (BookID) REFERENCES BOOK (BookID),
CONSTRAINT BOOKAUTHOR_FKEY2 FOREIGN KEY (AuthorID) REFERENCES AUTHOR (AuthorID)
);

-- CREATE TABLE CUSTOMER
CREATE TABLE CUSTOMER (
	CustomerID		VARCHAR(12)		NOT NULL,
	Name			VARCHAR(50)		NOT NULL,
CONSTRAINT CUSTOMER_PKEY PRIMARY KEY (CustomerID)
);

-- CREATE TABLE PURCHASE
CREATE TABLE PURCHASE (
	PurchaseID			VARCHAR(12)		NOT NULL,
	PurchaseQty			DECIMAL(4)		NOT NULL,
	PurchaseDate		DATE			NOT NULL,
	BookID			VARCHAR(12)		NOT NULL,
	CustomerID		VARCHAR(12)		NOT NULL,
CONSTRAINT PURCHASE_PKEY PRIMARY KEY (PurchaseID),
CONSTRAINT PURCHASE_FKEY1 FOREIGN KEY (BookID) REFERENCES BOOK (BookID),
CONSTRAINT PURCHASE_FKEY2 FOREIGN KEY (CustomerID) REFERENCES CUSTOMER (CustomerID)
);

-- CREATE TABLE ONLINEPURCHASE
CREATE TABLE ONLINEPURCHASE (
	PurchaseID		VARCHAR(12)		NOT NULL,
	OnlineType		VARCHAR(12)		NOT NULL,
CONSTRAINT ONLINEPURCHASE_PKEY PRIMARY KEY (PurchaseID),
CONSTRAINT ONLINEPURCHASE_FKEY1 FOREIGN KEY (PurchaseID) REFERENCES PURCHASE (PurchaseID)
);

-- CREATE TABLE WALKINPURCHASE
CREATE TABLE WALKINPURCHASE (
	PurchaseID		VARCHAR(12)		NOT NULL,
	ShopLocation	VARCHAR(50)		NOT NULL,
CONSTRAINT WALKINPURCHASE_PKEY PRIMARY KEY (PurchaseID),
CONSTRAINT WALKINPURCHASE_FKEY1 FOREIGN KEY (PurchaseID) REFERENCES PURCHASE (PurchaseID)
);
